#!/usr/bin/env python3
"""
GCM (Git Checkout Master) - Portable git workflow automation tool

Generated By: Cursor (Claude Sonnet 4)
"""

import argparse
import copy
import logging
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Optional, Any
import yaml


class GCMError(Exception):
    """Base exception for GCM operations"""

    pass


class GitError(GCMError):
    """Git operation specific errors"""

    pass


class ConfigError(GCMError):
    """Configuration related errors"""

    pass


class GCMConfig:
    """Configuration management for GCM"""

    DEFAULT_CONFIG = {
        "providers": {
            "github": {"username": None, "fork_remote": None, "vpn_command": None},
            "gitlab": {"username": None, "fork_remote": None, "vpn_command": None},
        },
        "remotes": {"upstream": "origin"},
        "branches": {"trunk_aliases": ["main", "master", "trunk"]},
        "behavior": {
            "auto_create_forks": False,
            "confirm_destructive": True,
            "parallel_operations": True,
        },
    }

    def __init__(self, config_path: Optional[Path] = None):
        self.config_path = config_path or self._find_config_file()
        self.config = self._load_config()

    def _find_config_file(self) -> Optional[Path]:
        """Find configuration file in standard locations"""
        candidates = [
            Path(".gcm.yaml"),  # Local repository
            Path(".gcm.yml"),  # Local repository (alt)
            Path.home() / ".gcm.yaml",  # User home
            Path.home() / ".gcm.yml",  # User home (alt)
            Path.home() / ".config" / "gcm.yaml",  # XDG config
            Path.home() / ".config" / "gcm.yml",  # XDG config (alt)
        ]

        for candidate in candidates:
            if candidate.exists():
                return candidate
        return None

    def _load_config(self) -> Dict[str, Any]:
        """Load configuration from file or use defaults"""
        config = copy.deepcopy(self.DEFAULT_CONFIG)

        if self.config_path and self.config_path.exists():
            try:
                with open(self.config_path, "r") as f:
                    user_config = yaml.safe_load(f) or {}
                self._merge_config(config, user_config)
            except Exception as e:
                raise ConfigError(f"Failed to load config from {self.config_path}: {e}")

        return config

    def _merge_config(self, base: Dict, overlay: Dict) -> None:
        """Recursively merge overlay config into base config"""
        for key, value in overlay.items():
            if key in base and isinstance(base[key], dict) and isinstance(value, dict):
                self._merge_config(base[key], value)
            else:
                base[key] = value

    def get_provider_config(self, provider: str) -> Dict[str, Any]:
        """Get configuration for a specific provider"""
        return self.config.get("providers", {}).get(provider, {})

    def get_username(self, provider: str) -> Optional[str]:
        """Get username for a provider"""
        return self.get_provider_config(provider).get("username")

    def get_fork_remote(self, provider: str) -> Optional[str]:
        """Get fork remote name for a provider"""
        return self.get_provider_config(provider).get("fork_remote")

    def get_vpn_command(self, provider: str) -> Optional[str]:
        """Get VPN command for a provider"""
        return self.get_provider_config(provider).get("vpn_command")


class GitRepository:
    """Git repository operations and state management"""

    def __init__(self, path: Path = None):
        self.path = path or Path.cwd()
        self.logger = logging.getLogger(__name__)
        self._ensure_git_repo()

    def _ensure_git_repo(self) -> None:
        """Ensure we're in a git repository"""
        result = self._run_git(["rev-parse", "--git-dir"], check=False)
        if result.returncode != 0:
            raise GitError(f"Not a git repository: {self.path}")

    def _run_git(
        self, args: List[str], check: bool = True, capture_output: bool = True
    ) -> subprocess.CompletedProcess:
        """Run git command with error handling"""
        cmd = ["git"] + args
        self.logger.debug(f"Running: {' '.join(cmd)}")

        try:
            result = subprocess.run(
                cmd,
                cwd=self.path,
                capture_output=capture_output,
                text=True,
                check=check,
            )
            self.logger.debug(f"Git command output: {result.stdout.strip()}")
            return result
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Git command failed: {' '.join(cmd)}")
            self.logger.error(f"Error: {e.stderr}")
            if check:
                raise GitError(f"Git command failed: {e.stderr}")
            return e

    def get_trunk_branch(self) -> str:
        """Detect the trunk/main branch from origin/HEAD"""
        result = self._run_git(
            ["symbolic-ref", "refs/remotes/origin/HEAD"], check=False
        )
        if result.returncode == 0:
            # Extract branch name from refs/remotes/origin/branch
            match = re.search(r"refs/remotes/origin/(.+)", result.stdout.strip())
            if match:
                return match.group(1)

        # Fallback: try common branch names
        for branch in ["main", "master", "trunk"]:
            result = self._run_git(
                ["rev-parse", "--verify", f"origin/{branch}"], check=False
            )
            if result.returncode == 0:
                return branch

        raise GitError("Could not determine trunk branch")

    def get_remotes(self) -> Dict[str, str]:
        """Get all remotes and their URLs"""
        result = self._run_git(["remote", "-v"])
        remotes = {}

        for line in result.stdout.strip().split("\n"):
            if not line:
                continue
            parts = line.split("\t")
            if len(parts) >= 2 and "(fetch)" in parts[1]:
                remote_name = parts[0]
                remote_url = parts[1].replace(" (fetch)", "")
                remotes[remote_name] = remote_url

        return remotes

    def detect_provider(self, remote_url: str) -> Optional[str]:
        """Detect git provider from remote URL"""
        if "github.com" in remote_url:
            return "github"
        elif "gitlab" in remote_url:
            return "gitlab"
        return None

    def get_current_branch(self) -> str:
        """Get current branch name"""
        result = self._run_git(["rev-parse", "--abbrev-ref", "HEAD"])
        return result.stdout.strip()

    def is_clean_working_tree(self) -> bool:
        """Check if working tree is clean"""
        result = self._run_git(["status", "--porcelain"])
        return not result.stdout.strip()

    def checkout_branch(self, branch: str, create_from_remote: bool = True) -> bool:
        """Checkout branch, optionally creating from remote"""
        try:
            if create_from_remote:
                # Try to create from origin first
                self._run_git(
                    ["checkout", "-b", branch, f"origin/{branch}"], check=False
                )

            # Fallback to regular checkout
            result = self._run_git(["checkout", branch], check=False)
            return result.returncode == 0
        except GitError:
            return False

    def pull(self) -> bool:
        """Pull latest changes"""
        try:
            self._run_git(["pull"])
            return True
        except GitError:
            return False

    def prune_remotes(self, parallel: bool = True) -> None:
        """Prune all remotes"""
        remotes = list(self.get_remotes().keys())

        if parallel:
            with ThreadPoolExecutor(max_workers=len(remotes)) as executor:
                futures = [
                    executor.submit(self._prune_remote, remote) for remote in remotes
                ]
                for future in as_completed(futures):
                    try:
                        future.result()
                    except Exception as e:
                        self.logger.warning(f"Failed to prune remote: {e}")
        else:
            for remote in remotes:
                self._prune_remote(remote)

    def _prune_remote(self, remote: str) -> None:
        """Prune a single remote"""
        self._run_git(["remote", "prune", remote])

    def get_merged_branches(self, trunk_branch: str) -> List[str]:
        """Get local branches that have been merged to trunk"""
        result = self._run_git(["branch", "--merged", trunk_branch])
        branches = []

        for line in result.stdout.strip().split("\n"):
            line = line.strip()
            if line and not line.startswith("*") and line != trunk_branch:
                branches.append(line)

        return branches

    def get_gone_branches(self) -> List[str]:
        """Get local branches where remote tracking branch is gone"""
        result = self._run_git(["branch", "-vv"])
        branches = []

        for line in result.stdout.strip().split("\n"):
            if ": gone]" in line:
                # Extract branch name (first word, removing *)
                branch = line.strip().split()[0].lstrip("*").strip()
                branches.append(branch)

        return branches

    def delete_branches(self, branches: List[str], parallel: bool = True) -> None:
        """Delete local branches"""
        if not branches:
            return

        if parallel:
            with ThreadPoolExecutor(max_workers=len(branches)) as executor:
                futures = [
                    executor.submit(self._delete_branch, branch) for branch in branches
                ]
                for future in as_completed(futures):
                    try:
                        future.result()
                    except Exception as e:
                        self.logger.warning(f"Failed to delete branch: {e}")
        else:
            for branch in branches:
                self._delete_branch(branch)

    def _delete_branch(self, branch: str) -> None:
        """Delete a single local branch"""
        self._run_git(["branch", "-d", branch], check=False)

    def get_remote_merged_branches(self, remote: str, trunk_branch: str) -> List[str]:
        """Get remote branches that have been merged to trunk"""
        result = self._run_git(["branch", "-r", "--merged", trunk_branch])
        branches = []

        for line in result.stdout.strip().split("\n"):
            line = line.strip()
            if line.startswith(f"{remote}/") and not line.endswith(f"/{trunk_branch}"):
                branch = line.replace(f"{remote}/", "")
                branches.append(branch)

        return branches

    def delete_remote_branches(
        self, remote: str, branches: List[str], parallel: bool = True
    ) -> None:
        """Delete remote branches"""
        if not branches:
            return

        if parallel:
            with ThreadPoolExecutor(max_workers=len(branches)) as executor:
                futures = [
                    executor.submit(self._delete_remote_branch, remote, branch)
                    for branch in branches
                ]
                for future in as_completed(futures):
                    try:
                        future.result()
                    except Exception as e:
                        self.logger.warning(f"Failed to delete remote branch: {e}")
        else:
            for branch in branches:
                self._delete_remote_branch(remote, branch)

    def _delete_remote_branch(self, remote: str, branch: str) -> None:
        """Delete a single remote branch"""
        self._run_git(["push", remote, f":{branch}", "--no-verify"], check=False)

    def push_branch(self, remote: str, branch: str) -> bool:
        """Push branch to remote"""
        try:
            self._run_git(["push", remote, branch, "--no-verify"])
            return True
        except GitError:
            return False

    def set_push_url(self, remote: str, url: str) -> None:
        """Set push URL for a remote"""
        self._run_git(["remote", "set-url", "--push", remote, url])

    def hard_reset_and_clean(self) -> None:
        """Perform hard reset and clean (DESTRUCTIVE)"""
        self._run_git(["clean", "-xdf"])
        self._run_git(["reset", "--hard", "HEAD"])


class GCM:
    """Main GCM application"""

    def __init__(self, config: GCMConfig, repo: GitRepository):
        self.config = config
        self.repo = repo
        self.logger = logging.getLogger(__name__)

    def run(self, make_remotes: bool = False, dry_run: bool = False) -> int:
        """Run the main GCM workflow"""
        try:
            self.logger.info("Starting GCM workflow...")

            # Detect repository provider and setup
            remotes = self.repo.get_remotes()
            origin_url = remotes.get("origin")
            if not origin_url:
                raise GCMError("No 'origin' remote found")

            provider = self.repo.detect_provider(origin_url)
            if not provider:
                self.logger.warning(f"Unknown provider for {origin_url}")

            # Connect VPN if needed
            if provider:
                self._ensure_vpn(provider, dry_run)

            # Get trunk branch
            trunk_branch = self.repo.get_trunk_branch()
            self.logger.info(f"Trunk branch: {trunk_branch}")

            # Setup fork remotes if requested
            if make_remotes and provider:
                self._setup_fork_remotes(provider, remotes, dry_run)

            # Disable push to origin if forks exist
            self._configure_origin_push(remotes, dry_run)

            # Checkout and update trunk
            self._checkout_and_update_trunk(trunk_branch, dry_run)

            # Prune remotes
            if not dry_run:
                self.logger.info("Pruning remotes...")
                self.repo.prune_remotes(
                    self.config.config["behavior"]["parallel_operations"]
                )

            # Clean up branches
            self._cleanup_branches(trunk_branch, remotes, dry_run)

            # Sync to forks
            if provider:
                self._sync_to_forks(provider, remotes, trunk_branch, dry_run)

            # Show final status
            if not dry_run:
                self._run_git(["status"], capture_output=False)

            self.logger.info("GCM workflow completed successfully")
            return 0

        except Exception as e:
            self.logger.error(f"GCM workflow failed: {e}")
            return 1

    def _ensure_vpn(self, provider: str, dry_run: bool) -> None:
        """Ensure VPN is connected if required"""
        vpn_command = self.config.get_vpn_command(provider)
        if vpn_command:
            self.logger.info(f"Connecting VPN for {provider}...")
            if not dry_run:
                try:
                    subprocess.run(vpn_command, shell=True, check=True)
                except subprocess.CalledProcessError as e:
                    self.logger.warning(f"VPN connection failed: {e}")

    def _setup_fork_remotes(
        self, provider: str, remotes: Dict[str, str], dry_run: bool
    ) -> None:
        """Setup fork remotes if they don't exist"""
        username = self.config.get_username(provider)
        fork_remote = self.config.get_fork_remote(provider)

        if not username or not fork_remote:
            self.logger.warning(f"No username/fork_remote configured for {provider}")
            return

        if fork_remote not in remotes:
            self.logger.info(f"Would create {fork_remote} remote for {provider}")
            # Note: Actual fork creation would need provider-specific logic

    def _configure_origin_push(self, remotes: Dict[str, str], dry_run: bool) -> None:
        """Disable push to origin if forks exist"""
        has_forks = any(
            self.config.get_fork_remote(provider) in remotes
            for provider in ["github", "gitlab"]
            if self.config.get_fork_remote(provider)
        )

        if has_forks:
            self.logger.info("Disabling push to origin (forks detected)")
            if not dry_run:
                self.repo.set_push_url("origin", "no_push")

    def _checkout_and_update_trunk(self, trunk_branch: str, dry_run: bool) -> None:
        """Checkout and update trunk branch"""
        self.logger.info(f"Checking out and updating {trunk_branch}...")

        if dry_run:
            self.logger.info(f"Would checkout {trunk_branch} and pull latest changes")
            return

        # Try checkout
        if not self.repo.checkout_branch(trunk_branch):
            if self._should_reset():
                self.repo.hard_reset_and_clean()
                if not self.repo.checkout_branch(trunk_branch):
                    raise GitError(f"Failed to checkout {trunk_branch}")
            else:
                raise GitError(f"Failed to checkout {trunk_branch}")

        # Try pull
        if not self.repo.pull():
            if self._should_reset():
                self.repo.hard_reset_and_clean()
                if not self.repo.pull():
                    raise GitError("Failed to pull latest changes")
            else:
                raise GitError("Failed to pull latest changes")

    def _should_reset(self) -> bool:
        """Ask user if they want to do a hard reset"""
        if not self.config.config["behavior"]["confirm_destructive"]:
            return False

        response = input(
            "\nDo a hard reset and clean (ALL UNSTAGED AND NEW CHANGES WILL BE DELETED) [yes/NO]: "
        )
        return response.lower() == "yes"

    def _cleanup_branches(
        self, trunk_branch: str, remotes: Dict[str, str], dry_run: bool
    ) -> None:
        """Clean up local and remote branches"""
        self.logger.info("Cleaning up branches...")

        # Clean up local branches
        merged_branches = self.repo.get_merged_branches(trunk_branch)
        gone_branches = self.repo.get_gone_branches()
        all_local_branches = list(set(merged_branches + gone_branches))

        if all_local_branches:
            self.logger.info(
                f"Deleting local branches: {', '.join(all_local_branches)}"
            )
            if not dry_run:
                self.repo.delete_branches(
                    all_local_branches,
                    self.config.config["behavior"]["parallel_operations"],
                )

        # Clean up remote fork branches
        for provider in ["github", "gitlab"]:
            fork_remote = self.config.get_fork_remote(provider)
            if fork_remote and fork_remote in remotes:
                remote_branches = self.repo.get_remote_merged_branches(
                    fork_remote, trunk_branch
                )
                if remote_branches:
                    self.logger.info(
                        f"Deleting {fork_remote} branches: {', '.join(remote_branches)}"
                    )
                    if not dry_run:
                        self.repo.delete_remote_branches(
                            fork_remote,
                            remote_branches,
                            self.config.config["behavior"]["parallel_operations"],
                        )

    def _sync_to_forks(
        self, provider: str, remotes: Dict[str, str], trunk_branch: str, dry_run: bool
    ) -> None:
        """Sync trunk branch to user forks"""
        fork_remote = self.config.get_fork_remote(provider)

        if fork_remote and fork_remote in remotes:
            self.logger.info(f"Syncing {trunk_branch} to {fork_remote}...")
            if not dry_run:
                self.repo.push_branch(fork_remote, trunk_branch)


def setup_logging(level: str = "INFO") -> None:
    """Setup logging configuration"""
    logging.basicConfig(
        level=getattr(logging, level.upper()),
        format="%(asctime)s - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def main() -> int:
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description="GCM - Git Checkout Master workflow automation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "-m", "--make-remotes", action="store_true", help="Create missing fork remotes"
    )

    parser.add_argument("--config", type=Path, help="Path to configuration file")

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes",
    )

    parser.add_argument(
        "--log-level",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        default="INFO",
        help="Set logging level",
    )

    args = parser.parse_args()

    setup_logging(args.log_level)

    try:
        config = GCMConfig(args.config)
        repo = GitRepository()
        gcm = GCM(config, repo)

        return gcm.run(make_remotes=args.make_remotes, dry_run=args.dry_run)

    except Exception as e:
        logging.error(f"Fatal error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
