# Generated By: Cursor (claude-4-sonnet)
# Makefile for GCM - Git Checkout Main

# Include modular makefiles
include make/env.mk
include make/test.mk
include make/lint.mk

.DEFAULT_GOAL := help
.PHONY: help

# Variables
PYTHON_MODULE := gcm
PYTHON_SCRIPT := gcm.py
PYTHON_VERSION := 3.8

# Python virtual environment
PYTHON := python3
VENV_DIR ?= .venv
VENV_PYTHON := $(VENV_DIR)/bin/python
VENV_PIP := $(VENV_DIR)/bin/pip
VENV_UV := $(VENV_DIR)/bin/uv

# Colors for output
BLUE := \033[34m
GREEN := \033[32m
YELLOW := \033[33m
RESET := \033[0m

help: ## Display this help message
	@echo "GCM - Git Checkout Main"
	@echo "========================="
	@echo ""
	@echo "Available targets:"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)