"""
Pytest fixtures for integration tests

Generated By: Cursor (claude-4-sonnet)
"""

import pytest
from pathlib import Path
import sys
import os

# Add project root to path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from tests.helpers.git_repo_factory import GitRepoFactory


@pytest.fixture
def repo_factory():
    """Provide a GitRepoFactory instance with automatic cleanup"""
    factory = GitRepoFactory()
    yield factory
    factory.cleanup()


@pytest.fixture
def clean_repo(repo_factory):
    """Provide a clean git repository"""
    return repo_factory.create_clean_repo()


@pytest.fixture
def dirty_repo(repo_factory):
    """Provide a git repository with uncommitted changes"""
    return repo_factory.create_dirty_repo()


@pytest.fixture
def repo_with_branches(repo_factory):
    """Provide a repository with various branch states"""
    return repo_factory.create_repo_with_branches(
        merged=["feature-1", "feature-2"],
        unmerged=["feature-3"],
        gone=["old-feature"]
    )


@pytest.fixture
def gcm_script():
    """Provide path to the GCM script"""
    return Path(__file__).parent.parent.parent / "gcm.py"