"""
Integration tests for different repository states

Generated By: Cursor (claude-4-sonnet)
"""

import subprocess
import sys


class TestRepositoryStates:
    """Test GCM behavior with different repository states"""

    def test_clean_repo_main_branch(self, clean_repo, gcm_script):
        """REPO-01: Clean repository with origin/HEAD pointing to main"""
        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=clean_repo,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        assert "main" in result.stderr  # Should detect main branch
        assert "Trunk branch: main" in result.stderr

    def test_clean_repo_main_branch(self, repo_factory, gcm_script):
        """REPO-02: Clean repository with origin/HEAD pointing to main"""
        repo_path = repo_factory.create_clean_repo("main")

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        assert "main" in result.stderr  # Should detect main branch
        assert "Trunk branch: main" in result.stderr

    def test_dirty_working_tree(self, dirty_repo, gcm_script):
        """REPO-03: Repository with dirty working tree"""
        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=dirty_repo,
            capture_output=True,
            text=True,
        )

        # Should complete in dry-run mode even with dirty working tree
        assert result.returncode == 0, f"GCM failed: {result.stderr}"

    def test_detached_head_state(self, repo_factory, gcm_script):
        """REPO-04: Repository in detached HEAD state"""
        repo_path = repo_factory.create_detached_head_repo()

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        # Should handle detached HEAD and show it would checkout trunk

    def test_no_origin_head(self, repo_factory, gcm_script):
        """REPO-05: Repository with no origin/HEAD set"""
        repo_path = repo_factory.create_repo_no_origin_head()

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        # Should fall back to detecting common branch names

    def test_no_common_trunk_branches(self, repo_factory, gcm_script):
        """REPO-06: Repository with no common trunk branches"""
        repo_path = repo_factory.create_repo_no_common_branches()

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )

        # Should fail with clear error message
        assert result.returncode == 1
        assert (
            "Could not determine trunk branch" in result.stderr
            or "trunk branch" in result.stderr.lower()
        )


class TestBranchManagement:
    """Test GCM branch management functionality"""

    def test_branch_cleanup_dry_run(self, repo_with_branches, gcm_script):
        """BRANCH-01-04: Test branch cleanup in dry-run mode"""
        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=repo_with_branches,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"

        # Should mention branch cleanup operations
        output = result.stderr.lower()
        assert "branch" in output or "cleanup" in output

    def test_current_branch_is_feature(self, repo_factory, gcm_script):
        """BRANCH-05: Current branch is feature branch when running GCM"""
        repo_path = repo_factory.create_repo_with_branches(unmerged=["current-feature"])

        # Switch to feature branch
        subprocess.run(
            ["git", "checkout", "current-feature"], cwd=repo_path, check=True
        )

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        # Should indicate it would switch to trunk branch


class TestConfiguration:
    """Test configuration handling in integration scenarios"""

    def test_local_config_file(self, clean_repo, gcm_script):
        """CONFIG-01: Local .gcm.yaml configuration"""
        config_content = """
providers:
  github:
    username: "testuser"
    fork_remote: "testuser"
"""
        config_file = clean_repo / ".gcm.yaml"
        config_file.write_text(config_content)

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=clean_repo,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        # Should load and use local configuration

    def test_invalid_config_file(self, clean_repo, gcm_script):
        """CONFIG-04: Invalid configuration file"""
        config_file = clean_repo / ".gcm.yaml"
        config_file.write_text("invalid: yaml: content: [")

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=clean_repo,
            capture_output=True,
            text=True,
        )

        # Should fail with config error
        assert result.returncode == 1
        assert "config" in result.stderr.lower() or "yaml" in result.stderr.lower()


class TestProviderDetection:
    """Test git provider detection"""

    def test_github_provider_detection(self, repo_factory, gcm_script):
        """PROVIDER-01: GitHub repository detection"""
        repo_path = repo_factory.create_repo_with_remotes(
            {"origin": "github", "myuser": "github"}
        )

        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        # Should detect GitHub provider

    def test_unknown_provider(self, clean_repo, gcm_script):
        """PROVIDER-03: Unknown provider"""
        # The clean_repo uses a local bare repository, which should be "unknown"
        result = subprocess.run(
            [sys.executable, str(gcm_script), "--dry-run"],
            cwd=clean_repo,
            capture_output=True,
            text=True,
        )

        assert result.returncode == 0, f"GCM failed: {result.stderr}"
        # Should handle unknown provider gracefully
