#!/bin/bash

MAKE_REMOTES=$1

# "trunk" is the primary branch, usually "main" but generalized to whatever origin/HEAD points to
BRANCH_TRUNK=$(git branch -a | grep "remotes/origin/HEAD" | sed 's|.* -> .*/\([^/]*\)|\1|g' | head -n1)

function reset_git_trunk {
    echo ""
    echo -n "Do a hard reset and clean (ALL UNSTAGED AND NEW CHANGES WILL BE DELETED) [yes/NO]: "
    read -r DO_RESET
    
    if [ "$DO_RESET" == "yes" ];
    then
        git clean -xdf
        git checkout -b $BRANCH_TRUNK origin/$BRANCH_TRUNK 2>/dev/null || git checkout $BRANCH_TRUNK
        git reset --hard HEAD
        git pull
    else
        exit -1
    fi
}

UPSTREAM_REPO=$(git remote -v | grep fetch | grep origin | sed 's|[^.@]*[@/]\([^/.]*\)\..*|\1|g')
HAVE_GITLAB_FORK=$(git remote -v | grep gitlab | grep fetch | grep ^gitlabuser | wc -l) # specifically look for a remote 'gitlabuser'
HAVE_GITHUB_FORK=$(git remote -v | grep github | grep fetch | grep ^githubuser | wc -l) # specifically look for a remote 'githubuser'

# if I have any forks disable set-url on push for origin
if [[ $HAVE_GITLAB_FORK -gt 0 ]] || [[ $HAVE_GITHUB_FORK -gt 0 ]];
then
    # disable push for origin, which should (must?) always be upstream.
    git remote set-url --push origin no_push
fi

if [ "$MAKE_REMOTES" == "-m" ];
then
    # make sure we have expected forks
    if [ "$UPSTREAM_REPO" == "gitlab" ] && [ "$HAVE_GITLAB_FORK" != "1" ];
    then
        remote-add gitlabuser
    fi

    if [ "$UPSTREAM_REPO" == "github" ] && [ "$HAVE_GITHUB_FORK" != "1" ];
    then
        remote-add githubuser
    fi

    HAVE_GITLAB_FORK=$(git remote -v | grep gitlab | grep fetch | grep gitlabuser | wc -l)
    HAVE_GITHUB_FORK=$(git remote -v | grep github | grep fetch | grep githubuser | wc -l)
fi

# make sure VPN is online
if [ "$UPSTREAM_REPO" == "gitlab" ];
then
    vpn-up
fi

echo "Checking out '$BRANCH_TRUNK' and pruning local branches..."
git checkout -b $BRANCH_TRUNK origin/$BRANCH_TRUNK 2>/dev/null || git checkout $BRANCH_TRUNK
CHECKOUT_STATUS=$?

if [ "$CHECKOUT_STATUS" != "0" ];
then
    echo "FAILURE: cannot checkout '$BRANCH_TRUNK'"

    # reset or exit:
    reset_git_trunk
fi

git pull
PULL_STATUS=$?

if [ "$PULL_STATUS" != "0" ];
then
    echo "FAILURE: unable to pull, see above error"

    # reset or exit:
    reset_git_trunk
fi

for R in $(git remote);
do
    git remote prune $R &
done

wait

# delete local branches where the upstream is gone
echo "Deleting local branches..."
git branch -vv | grep '\[.*/.*: gone\]' | awk '{print $1}' | xargs git branch -d 2>/dev/null &

# delete local branches that have been merged to current branch (which is now trunk)
for BRANCH in $(git branch -a | grep -v -e "remotes/" | grep -v $BRANCH_TRUNK | xargs);
do
    if [ "$(git branch --contains $BRANCH | grep "^\*" | wc -l)" == "1" ];
    then
        git branch -d $BRANCH &
    fi
done

wait

echo "Deleting remote branches..."
# delete remote branches that have been merged to current branch (which is now trunk)
for BRANCH in $(git branch -a | grep -e "remotes/githubuser" -e "remotes/gitlabuser" | grep -v $BRANCH_TRUNK | sed 's|remotes/\([^/]*\)\/|\1:|g' | xargs);
do
    # BRANCH format is <remote>:<branch>
    # ':' is used to easily support a branch name with / in it.
    # therefore, convert : to / for checking contains, so it's against the REMOTE branch
    if [ "$(git branch --contains $(echo $BRANCH | tr ':' '/') | grep "^\*" | wc -l)" == "1" ];
    then
        echo $BRANCH | awk -F: '{print "git push " $1 " :" $2 " --no-verify"}' | sh &
    fi
done

wait

# push origin trunk to my fork
if [ "$HAVE_GITHUB_FORK" == "1" ];
then
    echo "Pushing '$BRANCH_TRUNK' branch..."
    git push githubuser $BRANCH_TRUNK --no-verify
fi

if [ "$HAVE_GITLAB_FORK" == "1" ];
then
    echo "Pushing '$BRANCH_TRUNK' branch..."
    git push gitlabuser $BRANCH_TRUNK --no-verify
fi

wait

git status
