#!/bin/bash

# start vpn connection if it isn't already up, else noop

VPN_NAME=$1

# the host used by nslookup to check if on vpn, must be behind VPN!
NSLOOKUP_HOST=$2

LOCKFILE=/tmp/vpn-up.lock

echo {lock_fd}>$LOCKFILE || exit 1
# get lock, block until available
flock "$lock_fd" || { echo "ERROR: flock() failed: $?" >&2; exit 1; }
# unlock when script exits
trap "flock -u $lock_fd" EXIT

# inside lock

# check if on Red Hat networks (could be hard wired in at an office)
nslookup $NSLOOKUP_HOST -timeout=0 2>&1 >/dev/null
ON_RH_NETWORK=$?

if [ "$ON_RH_NETWORK" == "1" ];
then
    # not on a Red Hat network
    # check if vpn is up
    VPN_UP=$(nmcli con show --active | grep vpn | wc -l)
    if [ "$VPN_UP" == "0" ];
    then
        # vpn is not up, bring it up, no cli output
        nmcli con up id "$VPN_NAME" 2>/dev/null >/dev/null
    fi
fi
