"""
Unit tests for GitRepository class

Generated By: Cursor (claude-4-sonnet)
"""

import pytest
from unittest.mock import Mock, patch

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from gcm import GitRepository, GitError


class TestGitRepository:
    """Test cases for GitRepository class"""

    @patch("gcm.GitRepository._run_git")
    def test_git_repo_initialization_success(self, mock_run_git):
        """GIT-01: Repository initialization succeeds in valid git repository"""
        mock_result = Mock()
        mock_result.returncode = 0

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return mock_result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        assert repo is not None
        mock_run_git.assert_called_once_with(["rev-parse", "--git-dir"], check=False)

    @patch("gcm.GitRepository._run_git")
    def test_git_repo_initialization_failure(self, mock_run_git):
        """GIT-02: Repository initialization fails in non-git directory"""
        mock_result = Mock()
        mock_result.returncode = 1
        mock_run_git.return_value = mock_result

        with pytest.raises(GitError, match="Not a git repository"):
            GitRepository()

    @patch("gcm.GitRepository._run_git")
    def test_get_trunk_branch_from_origin_head(self, mock_run_git):
        """GIT-03: Trunk branch detection works from origin/HEAD"""
        mock_result = Mock()
        mock_result.returncode = 0
        mock_result.stdout = "refs/remotes/origin/main\n"

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return mock_result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        trunk = repo.get_trunk_branch()
        assert trunk == "main"

    @patch("gcm.GitRepository._run_git")
    def test_get_trunk_branch_fallback(self, mock_run_git):
        """GIT-04: Trunk branch detection fails when origin/HEAD is not set"""

        # First call (symbolic-ref) fails, no fallback
        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                # Git repo validation - return success
                result = Mock()
                result.returncode = 0
                return result
            else:
                result = Mock()
                result.returncode = 1
                return result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        with pytest.raises(GitError, match="Could not determine trunk branch"):
            repo.get_trunk_branch()

    @patch("gcm.GitRepository._run_git")
    def test_get_trunk_branch_not_found(self, mock_run_git):
        """GIT-05: Trunk branch detection fails when no common branches exist"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            else:
                result = Mock()
                result.returncode = 1
                return result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        with pytest.raises(GitError, match="Could not determine trunk branch"):
            repo.get_trunk_branch()

    @patch("gcm.GitRepository._run_git")
    def test_get_remotes(self, mock_run_git):
        """GIT-06: Remote detection parses git remote output correctly"""
        mock_result = Mock()
        mock_result.stdout = """origin\tgit@github.com:user/repo.git (fetch)
origin\tgit@github.com:user/repo.git (push)
upstream\tgit@github.com:upstream/repo.git (fetch)
upstream\tgit@github.com:upstream/repo.git (push)"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return mock_result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        remotes = repo.get_remotes()

        assert "origin" in remotes
        assert "upstream" in remotes
        assert remotes["origin"] == "git@github.com:user/repo.git"
        assert remotes["upstream"] == "git@github.com:upstream/repo.git"

    @patch("gcm.GitRepository._run_git")
    def test_detect_provider_github(self, mock_run_git):
        """GIT-07: Provider detection identifies GitHub correctly"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        provider = repo.detect_provider("git@github.com:user/repo.git")
        assert provider == "github"

        provider = repo.detect_provider("https://github.com/user/repo.git")
        assert provider == "github"

    @patch("gcm.GitRepository._run_git")
    def test_detect_provider_gitlab(self, mock_run_git):
        """GIT-08: Provider detection identifies GitLab correctly"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        provider = repo.detect_provider("git@gitlab.com:user/repo.git")
        assert provider == "gitlab"

        provider = repo.detect_provider("https://gitlab.example.com/user/repo.git")
        assert provider == "gitlab"

    @patch("gcm.GitRepository._run_git")
    def test_detect_provider_unknown(self, mock_run_git):
        """GIT-09: Provider detection returns None for unknown providers"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        provider = repo.detect_provider("git@example.com:user/repo.git")
        assert provider is None

    @patch("gcm.GitRepository._run_git")
    def test_is_clean_working_tree_clean(self, mock_run_git):
        """GIT-10: Clean working tree detection works when tree is clean"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "status" in args:
                result = Mock()
                result.stdout = ""
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        assert repo.is_clean_working_tree() is True

    @patch("gcm.GitRepository._run_git")
    def test_is_clean_working_tree_dirty(self, mock_run_git):
        """GIT-11: Clean working tree detection works when tree is dirty"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "status" in args:
                result = Mock()
                result.stdout = " M modified_file.txt\n?? untracked_file.txt\n"
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        assert repo.is_clean_working_tree() is False

    @patch("gcm.GitRepository._run_git")
    def test_checkout_branch_success(self, mock_run_git):
        """GIT-12: Branch checkout succeeds with valid branch"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "checkout" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        success = repo.checkout_branch("main")
        assert success is True

    @patch("gcm.GitRepository._run_git")
    def test_checkout_branch_failure(self, mock_run_git):
        """GIT-13: Branch checkout fails with invalid branch"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "checkout" in args:
                result = Mock()
                result.returncode = 1
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        success = repo.checkout_branch("nonexistent")
        assert success is False

    @patch("gcm.GitRepository._run_git")
    def test_get_merged_branches(self, mock_run_git):
        """GIT-14: Merged branch detection finds correct branches"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "--merged" in args:
                result = Mock()
                result.stdout = """  feature-branch
* main
  old-feature
  another-branch"""
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        merged = repo.get_merged_branches("main")

        assert "feature-branch" in merged
        assert "old-feature" in merged
        assert "another-branch" in merged
        assert "main" not in merged  # Current branch excluded

    @patch("gcm.GitRepository._run_git")
    def test_get_gone_branches(self, mock_run_git):
        """GIT-15: Gone branch detection finds branches with deleted upstreams"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "-vv" in args:
                result = Mock()
                result.stdout = """  feature-1    abc1234 [origin/feature-1] Latest commit
  feature-2    def5678 [origin/feature-2: gone] Old commit
* main         hij9012 [origin/main] Current commit
  feature-3    klm3456 [origin/feature-3: gone] Another old commit"""
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        gone = repo.get_gone_branches()

        assert "feature-2" in gone
        assert "feature-3" in gone
        assert "feature-1" not in gone
        assert "main" not in gone

    @patch("gcm.GitRepository._run_git")
    def test_git_command_logging(self, mock_run_git):
        """GIT-16: Git commands are properly logged for debugging"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()

        # Just verify that _run_git was called with the right args
        repo._run_git(["status"])
        mock_run_git.assert_called_with(["status"])

    @patch("gcm.GitRepository._run_git")
    def test_hard_reset_and_clean(self, mock_run_git):
        """GIT-17: Hard reset and clean executes correct git commands"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.hard_reset_and_clean()

        # Should call clean and reset
        calls = mock_run_git.call_args_list
        clean_called = any("clean" in str(call) for call in calls)
        reset_called = any("reset" in str(call) for call in calls)

        assert clean_called
        assert reset_called

    @patch("gcm.subprocess.run")
    def test_run_git_error_handling_with_check_true(self, mock_subprocess):
        """GIT-18: Error handling when check=True and command fails"""
        from subprocess import CalledProcessError

        # Create a CalledProcessError with stderr
        error = CalledProcessError(1, ["git", "status"], stderr="Command failed")

        def side_effect(*args, **kwargs):
            if "rev-parse" in str(args) and "--git-dir" in str(args):
                result = Mock()
                result.returncode = 0
                result.stdout = ""
                result.stderr = ""
                return result
            elif "status" in str(args):
                raise error
            result = Mock()
            result.returncode = 0
            result.stdout = ""
            result.stderr = ""
            return result

        mock_subprocess.side_effect = side_effect

        repo = GitRepository()

        # Should raise GitError when check=True (default)
        with pytest.raises(GitError, match="Git command failed: Command failed"):
            repo._run_git(["status"], check=True)

    @patch("gcm.subprocess.run")
    def test_run_git_error_handling_with_check_false(self, mock_subprocess):
        """GIT-19: Error handling when check=False returns CompletedProcess with error state"""
        from subprocess import CalledProcessError, CompletedProcess

        # Create a CalledProcessError
        error = CalledProcessError(1, ["git", "status"], stderr="Command failed")

        def side_effect(*args, **kwargs):
            if "rev-parse" in str(args) and "--git-dir" in str(args):
                result = Mock()
                result.returncode = 0
                result.stdout = ""
                result.stderr = ""
                return result
            elif "status" in str(args):
                raise error
            result = Mock()
            result.returncode = 0
            result.stdout = ""
            result.stderr = ""
            return result

        mock_subprocess.side_effect = side_effect

        repo = GitRepository()

        # Should return CompletedProcess with non-zero returncode when check=False
        result = repo._run_git(["status"], check=False)
        assert isinstance(result, CompletedProcess)
        assert result.returncode == 1

    @patch("gcm.GitRepository._run_git")
    def test_get_current_branch(self, mock_run_git):
        """GIT-20: Get current branch name"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "rev-parse" in args and "--abbrev-ref" in args:
                result = Mock()
                result.stdout = "feature-branch\n"
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        branch = repo.get_current_branch()

        assert branch == "feature-branch"

    @patch("gcm.GitRepository._run_git")
    def test_delete_branches_empty_list(self, mock_run_git):
        """GIT-21: Delete branches with empty list should return early"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.delete_branches([])

        # Should only call rev-parse for initialization, no branch deletion
        calls = [call for call in mock_run_git.call_args_list if "branch" in str(call)]
        assert len(calls) == 0

    @patch("gcm.GitRepository._run_git")
    def test_delete_branches_parallel_with_error(self, mock_run_git):
        """GIT-22: Delete branches in parallel mode with error handling"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "branch" in args and "problem-branch" in args:
                raise GitError("Cannot delete branch")
            elif "branch" in args:
                return Mock(returncode=0)
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()

        # Should handle errors gracefully and continue
        repo.delete_branches(["good-branch", "problem-branch"], parallel=True)

        # Should have attempted to delete both branches (plus initial repo check)
        branch_calls = [
            call for call in mock_run_git.call_args_list if "branch" in str(call)
        ]
        assert len(branch_calls) == 2

    @patch("gcm.GitRepository._run_git")
    def test_delete_branches_sequential(self, mock_run_git):
        """GIT-23: Delete branches in sequential mode"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "branch" in args:
                return Mock(returncode=0)
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.delete_branches(["branch1", "branch2"], parallel=False)

        # Should call _delete_branch for each branch sequentially (plus initial repo check)
        branch_calls = [
            call for call in mock_run_git.call_args_list if "branch" in str(call)
        ]
        assert len(branch_calls) == 2

    @patch("gcm.GitRepository._run_git")
    def test_get_remote_merged_branches(self, mock_run_git):
        """GIT-24: Get remote merged branches filters correctly"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "branch" in args and "--merged" in args:
                result = Mock()
                result.stdout = "  origin/feature1\n  origin/feature2\n  origin/main\n  other-remote/feature3\n"
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        branches = repo.get_remote_merged_branches("origin", "main")

        # Should only return origin branches that are not the trunk branch
        assert "feature1" in branches
        assert "feature2" in branches
        assert "main" not in branches  # trunk branch should be excluded
        assert "feature3" not in branches  # other remote should be excluded

    @patch("gcm.GitRepository._run_git")
    def test_delete_remote_branches_empty_list(self, mock_run_git):
        """GIT-25: Delete remote branches with empty list should return early"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.delete_remote_branches("origin", [])

        # Should only call rev-parse for initialization, no push commands
        push_calls = [
            call for call in mock_run_git.call_args_list if "push" in str(call)
        ]
        assert len(push_calls) == 0

    @patch("gcm.GitRepository._run_git")
    def test_delete_remote_branches_parallel_with_error(self, mock_run_git):
        """GIT-26: Delete remote branches in parallel mode with error handling"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "push" in args and "problem-branch" in str(args):
                raise GitError("Cannot delete remote branch")
            elif "push" in args:
                return Mock(returncode=0)
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()

        # Should handle errors gracefully and continue
        repo.delete_remote_branches(
            "origin", ["good-branch", "problem-branch"], parallel=True
        )

        # Should have attempted to delete both branches (plus initial repo check)
        push_calls = [
            call for call in mock_run_git.call_args_list if "push" in str(call)
        ]
        assert len(push_calls) == 2

    @patch("gcm.GitRepository._run_git")
    def test_delete_remote_branches_sequential(self, mock_run_git):
        """GIT-27: Delete remote branches in sequential mode"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "push" in args:
                return Mock(returncode=0)
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.delete_remote_branches("origin", ["branch1", "branch2"], parallel=False)

        # Should call push for each branch sequentially (plus initial repo check)
        push_calls = [
            call for call in mock_run_git.call_args_list if "push" in str(call)
        ]
        assert len(push_calls) == 2

    @patch("gcm.GitRepository._run_git")
    def test_push_branch_success(self, mock_run_git):
        """GIT-28: Push branch succeeds"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "push" in args:
                return Mock(returncode=0)
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        result = repo.push_branch("origin", "main")

        assert result is True

    @patch("gcm.GitRepository._run_git")
    def test_push_branch_failure(self, mock_run_git):
        """GIT-29: Push branch handles failure"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "push" in args:
                raise GitError("Push failed")
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        result = repo.push_branch("origin", "main")

        assert result is False

    @patch("gcm.GitRepository._run_git")
    def test_set_push_url(self, mock_run_git):
        """GIT-30: Set push URL for remote"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "remote" in args and "set-url" in args:
                return Mock(returncode=0)
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.set_push_url("origin", "git@github.com:user/repo.git")

        # Should call remote set-url with --push flag
        remote_calls = [
            call
            for call in mock_run_git.call_args_list
            if "remote" in str(call) and "set-url" in str(call)
        ]
        assert len(remote_calls) == 1

    @patch("gcm.GitRepository._run_git")
    def test_add_remote(self, mock_run_git):
        """GIT-31: Add remote and fetch from it"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "remote" in args and "add" in args:
                return Mock(returncode=0)
            elif "fetch" in args:
                return Mock(returncode=0)
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.add_remote("myuser", "git@github.com:myuser/repo.git")

        # Should call git remote add and then git fetch
        add_calls = [
            call
            for call in mock_run_git.call_args_list
            if "remote" in str(call) and "add" in str(call)
        ]
        fetch_calls = [
            call for call in mock_run_git.call_args_list if "fetch" in str(call)
        ]
        assert len(add_calls) == 1
        assert len(fetch_calls) == 1

    @patch("gcm.GitRepository._run_git")
    def test_convert_origin_to_fork_url_https(self, mock_run_git):
        """GIT-32: Convert HTTPS origin URL to fork SSH URL"""
        mock_run_git.return_value = Mock(returncode=0)
        repo = GitRepository()

        # Test HTTPS URL
        origin_url = "https://github.com/upstream/repo.git"
        fork_url = repo.convert_origin_to_fork_url(origin_url, "myuser")
        assert fork_url == "git@github.com:myuser/repo.git"

        # Test HTTPS URL without .git
        origin_url = "https://github.com/upstream/repo"
        fork_url = repo.convert_origin_to_fork_url(origin_url, "myuser")
        assert fork_url == "git@github.com:myuser/repo.git"

    @patch("gcm.GitRepository._run_git")
    def test_convert_origin_to_fork_url_ssh(self, mock_run_git):
        """GIT-33: Convert SSH origin URL to fork SSH URL"""
        mock_run_git.return_value = Mock(returncode=0)
        repo = GitRepository()

        # Test SSH URL
        origin_url = "git@github.com:upstream/repo.git"
        fork_url = repo.convert_origin_to_fork_url(origin_url, "myuser")
        assert fork_url == "git@github.com:myuser/repo.git"

        # Test SSH URL without .git
        origin_url = "git@github.com:upstream/repo"
        fork_url = repo.convert_origin_to_fork_url(origin_url, "myuser")
        assert fork_url == "git@github.com:myuser/repo.git"

    @patch("gcm.GitRepository._run_git")
    def test_convert_origin_to_fork_url_gitlab(self, mock_run_git):
        """GIT-34: Convert GitLab URLs to fork URLs"""
        mock_run_git.return_value = Mock(returncode=0)
        repo = GitRepository()

        # Test GitLab HTTPS
        origin_url = "https://gitlab.com/upstream/repo.git"
        fork_url = repo.convert_origin_to_fork_url(origin_url, "myuser")
        assert fork_url == "git@gitlab.com:myuser/repo.git"

        # Test GitLab SSH
        origin_url = "git@gitlab.com:upstream/repo.git"
        fork_url = repo.convert_origin_to_fork_url(origin_url, "myuser")
        assert fork_url == "git@gitlab.com:myuser/repo.git"

    @patch("gcm.GitRepository._run_git")
    def test_convert_origin_to_fork_url_invalid(self, mock_run_git):
        """GIT-35: Handle invalid origin URLs"""
        mock_run_git.return_value = Mock(returncode=0)
        repo = GitRepository()

        with pytest.raises(GitError, match="Unable to parse origin URL"):
            repo.convert_origin_to_fork_url("invalid-url", "myuser")
