"""
Unit tests for GitRepository class

Generated By: Cursor (claude-4-sonnet)
"""

import pytest
from unittest.mock import Mock, patch

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from gcm import GitRepository, GitError


class TestGitRepository:
    """Test cases for GitRepository class"""

    @patch("gcm.GitRepository._run_git")
    def test_git_repo_initialization_success(self, mock_run_git):
        """GIT-01: Repository initialization succeeds in valid git repository"""
        mock_result = Mock()
        mock_result.returncode = 0

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return mock_result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        assert repo is not None
        mock_run_git.assert_called_once_with(["rev-parse", "--git-dir"], check=False)

    @patch("gcm.GitRepository._run_git")
    def test_git_repo_initialization_failure(self, mock_run_git):
        """GIT-02: Repository initialization fails in non-git directory"""
        mock_result = Mock()
        mock_result.returncode = 1
        mock_run_git.return_value = mock_result

        with pytest.raises(GitError, match="Not a git repository"):
            GitRepository()

    @patch("gcm.GitRepository._run_git")
    def test_get_trunk_branch_from_origin_head(self, mock_run_git):
        """GIT-03: Trunk branch detection works from origin/HEAD"""
        mock_result = Mock()
        mock_result.returncode = 0
        mock_result.stdout = "refs/remotes/origin/main\n"

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return mock_result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        trunk = repo.get_trunk_branch()
        assert trunk == "main"

    @patch("gcm.GitRepository._run_git")
    def test_get_trunk_branch_fallback(self, mock_run_git):
        """GIT-04: Trunk branch detection falls back to common names"""

        # First call (symbolic-ref) fails, second call (main) succeeds
        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                # Git repo validation - return success
                result = Mock()
                result.returncode = 0
                return result
            elif "symbolic-ref" in args:
                result = Mock()
                result.returncode = 1
                return result
            elif "origin/main" in args:
                result = Mock()
                result.returncode = 0
                return result
            else:
                result = Mock()
                result.returncode = 1
                return result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        trunk = repo.get_trunk_branch()
        assert trunk == "main"

    @patch("gcm.GitRepository._run_git")
    def test_get_trunk_branch_not_found(self, mock_run_git):
        """GIT-05: Trunk branch detection fails when no common branches exist"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            else:
                result = Mock()
                result.returncode = 1
                return result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        with pytest.raises(GitError, match="Could not determine trunk branch"):
            repo.get_trunk_branch()

    @patch("gcm.GitRepository._run_git")
    def test_get_remotes(self, mock_run_git):
        """GIT-06: Remote detection parses git remote output correctly"""
        mock_result = Mock()
        mock_result.stdout = """origin\tgit@github.com:user/repo.git (fetch)
origin\tgit@github.com:user/repo.git (push)
upstream\tgit@github.com:upstream/repo.git (fetch)
upstream\tgit@github.com:upstream/repo.git (push)"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return mock_result

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        remotes = repo.get_remotes()

        assert "origin" in remotes
        assert "upstream" in remotes
        assert remotes["origin"] == "git@github.com:user/repo.git"
        assert remotes["upstream"] == "git@github.com:upstream/repo.git"

    @patch("gcm.GitRepository._run_git")
    def test_detect_provider_github(self, mock_run_git):
        """GIT-07: Provider detection identifies GitHub correctly"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        provider = repo.detect_provider("git@github.com:user/repo.git")
        assert provider == "github"

        provider = repo.detect_provider("https://github.com/user/repo.git")
        assert provider == "github"

    @patch("gcm.GitRepository._run_git")
    def test_detect_provider_gitlab(self, mock_run_git):
        """GIT-08: Provider detection identifies GitLab correctly"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        provider = repo.detect_provider("git@gitlab.com:user/repo.git")
        assert provider == "gitlab"

        provider = repo.detect_provider("https://gitlab.example.com/user/repo.git")
        assert provider == "gitlab"

    @patch("gcm.GitRepository._run_git")
    def test_detect_provider_unknown(self, mock_run_git):
        """GIT-09: Provider detection returns None for unknown providers"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        provider = repo.detect_provider("git@example.com:user/repo.git")
        assert provider is None

    @patch("gcm.GitRepository._run_git")
    def test_is_clean_working_tree_clean(self, mock_run_git):
        """GIT-10: Clean working tree detection works when tree is clean"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "status" in args:
                result = Mock()
                result.stdout = ""
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        assert repo.is_clean_working_tree() is True

    @patch("gcm.GitRepository._run_git")
    def test_is_clean_working_tree_dirty(self, mock_run_git):
        """GIT-11: Clean working tree detection works when tree is dirty"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "status" in args:
                result = Mock()
                result.stdout = " M modified_file.txt\n?? untracked_file.txt\n"
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        assert repo.is_clean_working_tree() is False

    @patch("gcm.GitRepository._run_git")
    def test_checkout_branch_success(self, mock_run_git):
        """GIT-12: Branch checkout succeeds with valid branch"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "checkout" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        success = repo.checkout_branch("main")
        assert success is True

    @patch("gcm.GitRepository._run_git")
    def test_checkout_branch_failure(self, mock_run_git):
        """GIT-13: Branch checkout fails with invalid branch"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "checkout" in args:
                result = Mock()
                result.returncode = 1
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        success = repo.checkout_branch("nonexistent")
        assert success is False

    @patch("gcm.GitRepository._run_git")
    def test_get_merged_branches(self, mock_run_git):
        """GIT-14: Merged branch detection finds correct branches"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "--merged" in args:
                result = Mock()
                result.stdout = """  feature-branch
* main
  old-feature
  another-branch"""
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        merged = repo.get_merged_branches("main")

        assert "feature-branch" in merged
        assert "old-feature" in merged
        assert "another-branch" in merged
        assert "main" not in merged  # Current branch excluded

    @patch("gcm.GitRepository._run_git")
    def test_get_gone_branches(self, mock_run_git):
        """GIT-15: Gone branch detection finds branches with deleted upstreams"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            elif "-vv" in args:
                result = Mock()
                result.stdout = """  feature-1    abc1234 [origin/feature-1] Latest commit
  feature-2    def5678 [origin/feature-2: gone] Old commit
* main         hij9012 [origin/main] Current commit
  feature-3    klm3456 [origin/feature-3: gone] Another old commit"""
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        gone = repo.get_gone_branches()

        assert "feature-2" in gone
        assert "feature-3" in gone
        assert "feature-1" not in gone
        assert "main" not in gone

    @patch("gcm.GitRepository._run_git")
    def test_git_command_logging(self, mock_run_git):
        """GIT-16: Git commands are properly logged for debugging"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()

        # Just verify that _run_git was called with the right args
        repo._run_git(["status"])
        mock_run_git.assert_called_with(["status"])

    @patch("gcm.GitRepository._run_git")
    def test_hard_reset_and_clean(self, mock_run_git):
        """GIT-17: Hard reset and clean executes correct git commands"""

        def side_effect(args, **kwargs):
            if "rev-parse" in args and "--git-dir" in args:
                result = Mock()
                result.returncode = 0
                return result
            return Mock()

        mock_run_git.side_effect = side_effect

        repo = GitRepository()
        repo.hard_reset_and_clean()

        # Should call clean and reset
        calls = mock_run_git.call_args_list
        clean_called = any("clean" in str(call) for call in calls)
        reset_called = any("reset" in str(call) for call in calls)

        assert clean_called
        assert reset_called
