"""
Unit tests for GCM configuration management

Generated By: Cursor (claude-4-sonnet)
"""

import pytest
import tempfile
import yaml
from pathlib import Path
from unittest.mock import patch

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from gcm import GCMConfig, ConfigError


class TestGCMConfig:
    """Test cases for GCMConfig class"""

    def test_default_config_loading(self):
        """CONFIG-01: Loading config works with default values when no config file exists"""
        with patch.object(Path, "exists", return_value=False):
            config = GCMConfig()
            assert config.config is not None
            assert "providers" in config.config
            assert "github" in config.config["providers"]
            assert "gitlab" in config.config["providers"]

    def test_config_file_loading(self):
        """CONFIG-02: Loading config works when config file exists"""
        test_config = {
            "providers": {"github": {"username": "testuser", "fork_remote": "testuser"}}
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            assert config.get_username("github") == "testuser"
            assert config.get_fork_remote("github") == "testuser"
        finally:
            config_path.unlink()

    def test_config_file_not_found_uses_defaults(self):
        """CONFIG-03: Loading config uses defaults when config file does not exist"""
        # Test that the default config has None values for usernames
        assert GCMConfig.DEFAULT_CONFIG["providers"]["github"]["username"] is None
        assert GCMConfig.DEFAULT_CONFIG["providers"]["github"]["fork_remote"] is None

        # Test that a completely isolated config instance uses defaults
        config = GCMConfig.__new__(GCMConfig)
        config.config = GCMConfig.DEFAULT_CONFIG.copy()
        assert config.get_username("github") is None
        assert config.get_fork_remote("github") is None

    def test_invalid_config_file_raises_error(self):
        """CONFIG-04: Loading config fails gracefully with invalid YAML"""
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            f.write("invalid: yaml: content: [")
            config_path = Path(f.name)

        try:
            with pytest.raises(ConfigError):
                GCMConfig(config_path)
        finally:
            config_path.unlink()

    def test_config_merge_preserves_defaults(self):
        """CONFIG-05: Config merging preserves default values for unspecified keys"""
        test_config = {"providers": {"github": {"username": "testuser"}}}

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            # Should have the override
            assert config.get_username("github") == "testuser"
            # Should preserve defaults for other providers
            assert "gitlab" in config.config["providers"]
            assert config.get_username("gitlab") is None
        finally:
            config_path.unlink()

    def test_get_provider_config(self):
        """CONFIG-06: Getting provider config returns correct values"""
        config = GCMConfig()
        github_config = config.get_provider_config("github")
        assert isinstance(github_config, dict)
        assert "username" in github_config
        assert "fork_remote" in github_config
        assert "vpn_command" in github_config

    def test_get_provider_config_unknown_provider(self):
        """CONFIG-07: Getting config for unknown provider returns empty dict"""
        config = GCMConfig()
        unknown_config = config.get_provider_config("unknown")
        assert unknown_config == {}

    def test_config_file_discovery(self):
        """CONFIG-08: Config file discovery finds files in standard locations"""
        # Test the _find_config_file method in isolation
        config = GCMConfig.__new__(GCMConfig)  # Create without calling __init__

        with patch.object(Path, "exists") as mock_exists:
            # First 5 candidates don't exist, 6th one does
            mock_exists.side_effect = [False, False, False, False, False, True]

            found_path = config._find_config_file()
            # Should have found a config file (the 6th candidate)
            assert found_path is not None
            assert isinstance(found_path, Path)

    def test_vpn_command_configuration(self):
        """CONFIG-09: VPN command configuration works correctly"""
        test_config = {"providers": {"gitlab": {"vpn_command": "custom-vpn-up"}}}

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            assert config.get_vpn_command("gitlab") == "custom-vpn-up"
            assert config.get_vpn_command("github") is None
        finally:
            config_path.unlink()

    def test_behavior_configuration(self):
        """CONFIG-10: Behavior configuration options work correctly"""
        test_config = {
            "behavior": {"confirm_destructive": False, "parallel_operations": False}
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            assert config.config["behavior"]["confirm_destructive"] is False
            assert config.config["behavior"]["parallel_operations"] is False
        finally:
            config_path.unlink()

    def test_get_username_with_provider(self):
        """CONFIG-11: Get username for configured provider"""
        test_config = {"providers": {"github": {"username": "testuser"}}}

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            username = config.get_username("github")
            assert username == "testuser"
        finally:
            config_path.unlink()

    def test_get_username_with_unknown_provider(self):
        """CONFIG-12: Get username for unknown provider returns None"""
        config = GCMConfig()
        username = config.get_username("unknown")
        assert username is None

    def test_get_fork_remote_with_provider(self):
        """CONFIG-13: Get fork remote for configured provider"""
        test_config = {"providers": {"github": {"fork_remote": "testuser"}}}

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            fork_remote = config.get_fork_remote("github")
            assert fork_remote == "testuser"
        finally:
            config_path.unlink()

    def test_get_fork_remote_with_unknown_provider(self):
        """CONFIG-14: Get fork remote for unknown provider returns None"""
        config = GCMConfig()
        fork_remote = config.get_fork_remote("unknown")
        assert fork_remote is None

    def test_get_vpn_command_with_provider(self):
        """CONFIG-15: Get VPN command for configured provider"""
        test_config = {"providers": {"github": {"vpn_command": "vpn connect github"}}}

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            vpn_command = config.get_vpn_command("github")
            assert vpn_command == "vpn connect github"
        finally:
            config_path.unlink()

    def test_get_vpn_command_with_unknown_provider(self):
        """CONFIG-16: Get VPN command for unknown provider returns None"""
        config = GCMConfig()
        vpn_command = config.get_vpn_command("unknown")
        assert vpn_command is None

    def test_config_file_discovery_yml_extension(self):
        """CONFIG-17: Config file discovery with .yml extension"""
        test_config = {"providers": {"github": {"username": "testuser"}}}

        # Test .yml extension instead of .yaml
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            # Patch the _find_config_file to return our test file
            with patch.object(GCMConfig, "_find_config_file", return_value=config_path):
                config = GCMConfig()
                assert config.get_username("github") == "testuser"
        finally:
            config_path.unlink()

    def test_merge_config_deep_nesting(self):
        """CONFIG-18: Deep config merge with nested dictionaries"""
        test_config = {
            "providers": {
                "github": {"username": "testuser"},
                "gitlab": {"username": "gitlabuser", "vpn_command": "vpn gitlab"},
            },
            "behavior": {"confirm_destructive": False},
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            yaml.dump(test_config, f)
            config_path = Path(f.name)

        try:
            config = GCMConfig(config_path)
            # Should preserve default values while overlaying user config
            assert config.config["providers"]["github"]["username"] == "testuser"
            assert (
                config.config["providers"]["github"]["fork_remote"] is None
            )  # Default
            assert config.config["providers"]["gitlab"]["username"] == "gitlabuser"
            assert config.config["providers"]["gitlab"]["vpn_command"] == "vpn gitlab"
            assert config.config["behavior"]["confirm_destructive"] is False
            assert (
                config.config["behavior"]["parallel_operations"] is True
            )  # Default preserved
        finally:
            config_path.unlink()
