"""
Unit tests for main GCM workflow

Generated By: Cursor (claude-4-sonnet)
"""

import pytest
from unittest.mock import Mock, patch

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from gcm import GCM, GitError


class TestGCMWorkflow:
    """Test cases for main GCM workflow"""

    @patch("gcm.GitRepository")
    @patch("gcm.GCMConfig")
    def test_gcm_initialization(self, mock_config, mock_repo):
        """MAIN-01: GCM initializes correctly with config and repository"""
        config = Mock()
        repo = Mock()

        gcm = GCM(config, repo)
        assert gcm.config == config
        assert gcm.repo == repo

    def test_origin_push_disabled_with_forks(self):
        """MAIN-05: Origin push is disabled when forks are detected"""
        config = Mock()
        config.get_fork_remote.side_effect = lambda provider: {
            "github": "myuser",
            "gitlab": None,
        }.get(provider)

        repo = Mock()
        gcm = GCM(config, repo)

        remotes = {"origin": "upstream_url", "myuser": "fork_url"}

        gcm._configure_origin_push(remotes, dry_run=False)
        repo.set_push_url.assert_called_once_with("origin", "no_push")

    def test_origin_push_not_disabled_without_forks(self):
        """MAIN-06: Origin push is not disabled when no forks are detected"""
        config = Mock()
        config.get_fork_remote.return_value = None

        repo = Mock()
        gcm = GCM(config, repo)

        remotes = {"origin": "upstream_url"}

        gcm._configure_origin_push(remotes, dry_run=False)
        repo.set_push_url.assert_not_called()

    def test_checkout_trunk_success(self):
        """MAIN-07: Trunk checkout and update succeeds normally"""
        config = Mock()
        repo = Mock()
        repo.checkout_branch.return_value = True
        repo.pull.return_value = True

        gcm = GCM(config, repo)
        gcm._checkout_and_update_trunk("main", dry_run=False)

        repo.checkout_branch.assert_called_once_with("main")
        repo.pull.assert_called_once()

    def test_checkout_trunk_with_reset(self):
        """MAIN-08: Trunk checkout handles failure with user confirmation for reset"""
        config = Mock()
        config.config = {"behavior": {"confirm_destructive": True}}

        repo = Mock()
        repo.checkout_branch.side_effect = [
            False,
            True,
        ]  # Fail first, succeed after reset
        repo.pull.return_value = True

        gcm = GCM(config, repo)

        with patch.object(gcm, "_should_reset", return_value=True):
            gcm._checkout_and_update_trunk("main", dry_run=False)
            repo.hard_reset_and_clean.assert_called_once()

    def test_checkout_trunk_reset_declined(self):
        """MAIN-09: Trunk checkout fails when user declines reset"""
        config = Mock()
        config.config = {"behavior": {"confirm_destructive": True}}

        repo = Mock()
        repo.checkout_branch.return_value = False

        gcm = GCM(config, repo)

        with patch.object(gcm, "_should_reset", return_value=False):
            with pytest.raises(GitError):
                gcm._checkout_and_update_trunk("main", dry_run=False)

    def test_branch_cleanup_merged_and_gone(self):
        """MAIN-10: Branch cleanup removes both merged and gone branches"""
        config = Mock()
        config.config = {"behavior": {"parallel_operations": True}}

        repo = Mock()
        repo.get_merged_branches.return_value = ["feature-1", "feature-2"]
        repo.get_gone_branches.return_value = ["old-feature"]
        repo.get_remote_merged_branches.return_value = ["remote-feature"]

        gcm = GCM(config, repo)
        remotes = {"origin": "upstream", "myuser": "fork"}

        gcm._cleanup_branches("main", remotes, dry_run=False)

        # Should delete local branches (order doesn't matter)
        called_args = repo.delete_branches.call_args[0]
        assert set(called_args[0]) == {"feature-1", "feature-2", "old-feature"}
        assert called_args[1] is True

    def test_sync_to_forks_success(self):
        """MAIN-11: Fork synchronization pushes trunk to configured forks"""
        config = Mock()
        config.get_fork_remote.return_value = "myuser"

        repo = Mock()
        repo.push_branch.return_value = True

        gcm = GCM(config, repo)
        remotes = {"origin": "upstream", "myuser": "fork"}

        gcm._sync_to_forks("github", remotes, "main", dry_run=False)
        repo.push_branch.assert_called_once_with("myuser", "main")

    def test_sync_to_forks_no_remote(self):
        """MAIN-12: Fork synchronization skips when fork remote doesn't exist"""
        config = Mock()
        config.get_fork_remote.return_value = "myuser"

        repo = Mock()
        gcm = GCM(config, repo)
        remotes = {"origin": "upstream"}  # No fork remote

        gcm._sync_to_forks("github", remotes, "main", dry_run=False)
        repo.push_branch.assert_not_called()

    def test_dry_run_mode(self):
        """MAIN-13: Dry-run mode shows actions without executing them"""
        config = Mock()
        config.config = {"behavior": {"parallel_operations": True}}

        config.get_username.return_value = None
        config.get_fork_remote.return_value = None

        repo = Mock()
        repo.get_remotes.return_value = {"origin": "git@github.com:user/repo.git"}
        repo.detect_provider.return_value = "github"
        repo.get_trunk_branch.return_value = "main"
        repo.get_merged_branches.return_value = []
        repo.get_gone_branches.return_value = []

        gcm = GCM(config, repo)

        # Should complete without errors and without calling destructive operations
        result = gcm.run(dry_run=True)
        assert result == 0

        # Should not call actual git operations
        repo.checkout_branch.assert_not_called()
        repo.pull.assert_not_called()
        repo.prune_remotes.assert_not_called()

    def test_error_handling_no_origin(self):
        """MAIN-14: Error handling works when no origin remote exists"""
        config = Mock()
        repo = Mock()
        repo.get_remotes.return_value = {}  # No remotes

        gcm = GCM(config, repo)

        result = gcm.run()
        assert result == 1  # Should return error code

    def test_parallel_operations_configuration(self):
        """MAIN-15: Parallel operations are controlled by configuration"""
        config = Mock()
        config.config = {"behavior": {"parallel_operations": False}}

        repo = Mock()
        repo.get_merged_branches.return_value = ["feature"]
        repo.get_gone_branches.return_value = []

        gcm = GCM(config, repo)
        remotes = {"origin": "upstream"}

        gcm._cleanup_branches("main", remotes, dry_run=False)

        # Should pass parallel_operations=False
        repo.delete_branches.assert_called_with(["feature"], False)

    @patch("gcm.main")
    def test_command_line_interface(self, mock_main):
        """MAIN-16: Command line interface parses arguments correctly"""
        mock_main.return_value = 0

        with patch("sys.argv", ["gcm.py", "-m", "--dry-run"]):
            # Import and test would happen here in a real CLI test
            pass

        # This test would need more sophisticated CLI testing framework
        # For now, just verify the main function exists
        assert callable(mock_main)

    @patch("gcm.GitRepository")
    @patch("gcm.GCMConfig")
    @patch("gcm.GCM")
    def test_main_function_success(
        self, mock_gcm_class, mock_config_class, mock_repo_class
    ):
        """MAIN-17: Main function creates objects and runs successfully"""
        from gcm import main

        # Setup mocks
        mock_config = Mock()
        mock_config_class.return_value = mock_config

        mock_repo = Mock()
        mock_repo_class.return_value = mock_repo

        mock_gcm = Mock()
        mock_gcm.run.return_value = 0
        mock_gcm_class.return_value = mock_gcm

        # Mock sys.argv to avoid argparse issues
        with patch("sys.argv", ["gcm.py"]):
            result = main()

        assert result == 0
        mock_config_class.assert_called_once()
        mock_repo_class.assert_called_once()
        mock_gcm_class.assert_called_once_with(mock_config, mock_repo)
        mock_gcm.run.assert_called_once()

    @patch("gcm.GitRepository")
    @patch("gcm.GCMConfig")
    def test_main_function_error_handling(self, mock_config_class, mock_repo_class):
        """MAIN-18: Main function handles exceptions and returns error code"""
        from gcm import main

        # Make config initialization raise an exception
        mock_config_class.side_effect = Exception("Config error")

        with patch("sys.argv", ["gcm.py"]):
            result = main()

        assert result == 1

    @patch("gcm.logging")
    def test_setup_logging_default(self, mock_logging):
        """MAIN-19: Setup logging with default level"""
        from gcm import setup_logging

        setup_logging()

        mock_logging.basicConfig.assert_called_once()
        call_args = mock_logging.basicConfig.call_args
        assert call_args[1]["level"] == mock_logging.INFO

    @patch("gcm.logging")
    def test_setup_logging_custom_level(self, mock_logging):
        """MAIN-20: Setup logging with custom level"""
        from gcm import setup_logging

        setup_logging("DEBUG")

        mock_logging.basicConfig.assert_called_once()
        call_args = mock_logging.basicConfig.call_args
        assert call_args[1]["level"] == mock_logging.DEBUG

    @patch(
        "sys.argv",
        [
            "gcm.py",
            "--config",
            "/path/to/config.yaml",
            "--dry-run",
            "--log-level",
            "DEBUG",
        ],
    )
    @patch("gcm.GitRepository")
    @patch("gcm.GCMConfig")
    @patch("gcm.GCM")
    def test_main_with_all_arguments(
        self, mock_gcm_class, mock_config_class, mock_repo_class
    ):
        """MAIN-21: Main function with all command line arguments"""
        from gcm import main
        from pathlib import Path

        # Setup mocks
        mock_config = Mock()
        mock_config_class.return_value = mock_config

        mock_repo = Mock()
        mock_repo_class.return_value = mock_repo

        mock_gcm = Mock()
        mock_gcm.run.return_value = 0
        mock_gcm_class.return_value = mock_gcm

        result = main()

        assert result == 0
        # Verify config was created with specified path
        mock_config_class.assert_called_once_with(Path("/path/to/config.yaml"))
        # Verify GCM run was called with correct arguments
        mock_gcm.run.assert_called_once_with(make_remotes=False, dry_run=True)

    def test_setup_fork_remotes_missing_config(self):
        """MAIN-26: Setup fork remotes with missing configuration"""
        config = Mock()
        config.get_username.return_value = None
        config.get_fork_remote.return_value = None
        repo = Mock()

        gcm = GCM(config, repo)

        # Should return early when username/fork_remote not configured
        gcm._setup_fork_remotes("github", {}, dry_run=False)

        config.get_username.assert_called_once_with("github")
        config.get_fork_remote.assert_called_once_with("github")

    def test_setup_fork_remotes_already_exists(self):
        """MAIN-27: Setup fork remotes when remote already exists"""
        config = Mock()
        config.get_username.return_value = "testuser"
        config.get_fork_remote.return_value = "testuser"
        repo = Mock()

        gcm = GCM(config, repo)

        remotes = {"origin": "upstream", "testuser": "fork"}

        # Should not attempt to create when remote already exists
        gcm._setup_fork_remotes("github", remotes, dry_run=False)

        # Just verify the config methods were called
        config.get_username.assert_called_once_with("github")
        config.get_fork_remote.assert_called_once_with("github")

    def test_setup_fork_remotes_new_remote(self):
        """MAIN-28: Setup fork remotes creates new remote"""
        config = Mock()
        config.get_username.return_value = "testuser"
        config.get_fork_remote.return_value = "testuser"
        repo = Mock()

        gcm = GCM(config, repo)

        remotes = {"origin": "upstream"}  # No fork remote exists

        # Should log that it would create the remote
        gcm._setup_fork_remotes("github", remotes, dry_run=False)

        config.get_username.assert_called_once_with("github")
        config.get_fork_remote.assert_called_once_with("github")
