"""
Git Repository Factory for Integration Tests

Generated By: Cursor (Claude Sonnet 4)
"""

import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, List, Optional


class GitRepoFactory:
    """Factory for creating test git repositories with specific states"""
    
    def __init__(self):
        self.temp_dirs = []
    
    def cleanup(self):
        """Clean up all created temporary directories"""
        for temp_dir in self.temp_dirs:
            if temp_dir.exists():
                shutil.rmtree(temp_dir)
        self.temp_dirs.clear()
    
    def _create_temp_dir(self) -> Path:
        """Create a temporary directory and track it for cleanup"""
        temp_dir = Path(tempfile.mkdtemp(prefix="gcm_test_"))
        self.temp_dirs.append(temp_dir)
        return temp_dir
    
    def _run_git(self, repo_path: Path, cmd: List[str], check: bool = True) -> subprocess.CompletedProcess:
        """Run git command in repository"""
        git_cmd = ["git"] + cmd
        return subprocess.run(
            git_cmd,
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=check
        )
    
    def _init_repo(self, repo_path: Path, trunk_branch: str = "main") -> None:
        """Initialize a git repository with basic setup"""
        # Initialize repo
        self._run_git(repo_path, ["init", "-b", trunk_branch])
        
        # Configure git user (required for commits)
        self._run_git(repo_path, ["config", "user.name", "Test User"])
        self._run_git(repo_path, ["config", "user.email", "test@example.com"])
        
        # Create initial commit
        (repo_path / "README.md").write_text("# Test Repository\n")
        self._run_git(repo_path, ["add", "README.md"])
        self._run_git(repo_path, ["commit", "-m", "Initial commit"])
    
    def _create_bare_remote(self, name: str = "origin") -> Path:
        """Create a bare repository to use as a remote"""
        bare_path = self._create_temp_dir() / f"{name}.git"
        subprocess.run(["git", "init", "--bare", str(bare_path)], check=True)
        return bare_path
    
    def create_clean_repo(self, trunk_branch: str = "main") -> Path:
        """REPO-01: Create a clean repository with origin/HEAD pointing to trunk"""
        repo_path = self._create_temp_dir() / "repo"
        repo_path.mkdir()
        
        # Create bare remote
        bare_remote = self._create_bare_remote()
        
        # Initialize and setup repo
        self._init_repo(repo_path, trunk_branch)
        
        # Add remote and push
        self._run_git(repo_path, ["remote", "add", "origin", str(bare_remote)])
        self._run_git(repo_path, ["push", "-u", "origin", trunk_branch])
        
        # Set origin/HEAD
        self._run_git(repo_path, ["remote", "set-head", "origin", trunk_branch])
        
        return repo_path
    
    def create_dirty_repo(self, trunk_branch: str = "main") -> Path:
        """REPO-03: Create repository with dirty working tree"""
        repo_path = self.create_clean_repo(trunk_branch)
        
        # Create uncommitted changes
        (repo_path / "dirty_file.txt").write_text("Uncommitted changes\n")
        (repo_path / "README.md").write_text("# Modified README\nUncommitted changes\n")
        
        # Create untracked file
        (repo_path / "untracked.txt").write_text("Untracked file\n")
        
        return repo_path
    
    def create_detached_head_repo(self, trunk_branch: str = "main") -> Path:
        """REPO-04: Create repository in detached HEAD state"""
        repo_path = self.create_clean_repo(trunk_branch)
        
        # Get first commit hash
        result = self._run_git(repo_path, ["rev-list", "--max-count=1", trunk_branch])
        first_commit = result.stdout.strip()
        
        # Checkout detached HEAD
        self._run_git(repo_path, ["checkout", first_commit])
        
        return repo_path
    
    def create_repo_with_branches(
        self, 
        merged: List[str] = None, 
        unmerged: List[str] = None, 
        gone: List[str] = None,
        trunk_branch: str = "main"
    ) -> Path:
        """BRANCH-01-04: Create repository with various branch states"""
        repo_path = self.create_clean_repo(trunk_branch)
        merged = merged or []
        unmerged = unmerged or []
        gone = gone or []
        
        # Create and merge branches
        for branch in merged:
            self._run_git(repo_path, ["checkout", "-b", branch])
            (repo_path / f"{branch}.txt").write_text(f"Feature {branch}\n")
            self._run_git(repo_path, ["add", f"{branch}.txt"])
            self._run_git(repo_path, ["commit", "-m", f"Add {branch} feature"])
            
            # Push branch
            self._run_git(repo_path, ["push", "origin", branch])
            
            # Merge to trunk
            self._run_git(repo_path, ["checkout", trunk_branch])
            self._run_git(repo_path, ["merge", "--no-ff", branch, "-m", f"Merge {branch}"])
            self._run_git(repo_path, ["push", "origin", trunk_branch])
        
        # Create unmerged branches
        for branch in unmerged:
            self._run_git(repo_path, ["checkout", "-b", branch])
            (repo_path / f"{branch}.txt").write_text(f"Unmerged feature {branch}\n")
            self._run_git(repo_path, ["add", f"{branch}.txt"])
            self._run_git(repo_path, ["commit", "-m", f"Add unmerged {branch} feature"])
            self._run_git(repo_path, ["push", "origin", branch])
        
        # Create branches that will be "gone" (deleted from remote but exist locally)
        for branch in gone:
            self._run_git(repo_path, ["checkout", "-b", branch])
            (repo_path / f"{branch}.txt").write_text(f"Gone feature {branch}\n")
            self._run_git(repo_path, ["add", f"{branch}.txt"])
            self._run_git(repo_path, ["commit", "-m", f"Add {branch} feature"])
            self._run_git(repo_path, ["push", "origin", branch])
            
            # Delete from remote (simulating branch being deleted)
            self._run_git(repo_path, ["push", "origin", f":{branch}"])
        
        # Return to trunk
        self._run_git(repo_path, ["checkout", trunk_branch])
        
        return repo_path
    
    def create_repo_with_remotes(self, remotes: Dict[str, str], trunk_branch: str = "main") -> Path:
        """REMOTE-01-04: Create repository with multiple remotes"""
        repo_path = self.create_clean_repo(trunk_branch)
        
        # Add additional remotes
        for remote_name, remote_type in remotes.items():
            if remote_name != "origin":  # origin already exists
                if remote_type == "github":
                    remote_url = f"git@github.com:testuser/testrepo.git"
                elif remote_type == "gitlab":
                    remote_url = f"git@gitlab.example.com:testuser/testrepo.git"
                else:
                    # Create another bare repository
                    bare_remote = self._create_bare_remote(remote_name)
                    remote_url = str(bare_remote)
                
                self._run_git(repo_path, ["remote", "add", remote_name, remote_url])
        
        return repo_path
    
    def create_conflicted_repo(self, trunk_branch: str = "main") -> Path:
        """CONFLICT-01: Create repository with merge conflicts"""
        repo_path = self.create_clean_repo(trunk_branch)
        
        # Create a file that will conflict
        conflict_file = repo_path / "conflict.txt"
        conflict_file.write_text("Original content\n")
        self._run_git(repo_path, ["add", "conflict.txt"])
        self._run_git(repo_path, ["commit", "-m", "Add conflict file"])
        self._run_git(repo_path, ["push", "origin", trunk_branch])
        
        # Create a conflicting change locally
        conflict_file.write_text("Local changes\n")
        self._run_git(repo_path, ["add", "conflict.txt"])
        self._run_git(repo_path, ["commit", "-m", "Local changes"])
        
        # Simulate remote changes by creating them in a different clone
        remote_repo = self._create_temp_dir() / "remote_repo"
        self._run_git(Path.cwd(), ["clone", str(repo_path / ".git"), str(remote_repo)])
        
        # Reset to the commit before local changes
        result = self._run_git(repo_path, ["rev-parse", "HEAD~1"])
        previous_commit = result.stdout.strip()
        self._run_git(repo_path, ["reset", "--hard", previous_commit])
        
        # Make different changes to the same file
        conflict_file.write_text("Remote changes\n")
        self._run_git(repo_path, ["add", "conflict.txt"])
        self._run_git(repo_path, ["commit", "-m", "Remote changes"])
        self._run_git(repo_path, ["push", "origin", trunk_branch])
        
        # Now the local repo is behind and will conflict on pull
        self._run_git(repo_path, ["reset", "--hard", previous_commit])
        conflict_file.write_text("Local changes\n")
        self._run_git(repo_path, ["add", "conflict.txt"])
        self._run_git(repo_path, ["commit", "-m", "Local changes"])
        
        return repo_path
    
    def create_repo_no_origin_head(self, trunk_branch: str = "main") -> Path:
        """REPO-05: Create repository with no origin/HEAD set"""
        repo_path = self.create_clean_repo(trunk_branch)
        
        # Remove origin/HEAD
        self._run_git(repo_path, ["remote", "set-head", "origin", "-d"])
        
        return repo_path
    
    def create_repo_no_common_branches(self) -> Path:
        """REPO-06: Create repository with no common trunk branches"""
        repo_path = self._create_temp_dir() / "repo"
        repo_path.mkdir()
        
        # Create bare remote
        bare_remote = self._create_bare_remote()
        
        # Initialize with non-standard branch name
        self._init_repo(repo_path, "development")
        
        # Add remote and push
        self._run_git(repo_path, ["remote", "add", "origin", str(bare_remote)])
        self._run_git(repo_path, ["push", "-u", "origin", "development"])
        
        # Don't set origin/HEAD, and no main/master branches exist
        
        return repo_path