name: GCM PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Set up environment and dependencies
      run: make requirements-dev
    
    - name: Run linting
      run: make lint
    
    - name: Run tests
      run: make test
